### ISSUE TITLE
What version of lwIP did you use to benchmark and test?

### ISSUE THREAD

**Issue by likewise** [yasukata/simple-lwip-dpdk#9]
The project seems not to specify the exact lwIP version used. Do you still know?

**Comment by yasukata** [comment]
Thank you for your message.

Please find the version of lwIP in Makefile, specifically at https://github.com/yasukata/tinyhttpd-lwip-dpdk/blob/7df3b9952911404fe99a60346e9089c4415b4bec/Makefile#L9

**Comment by likewise** [comment]
(A late) Thanks.
